# Generated by Django 3.1 on 2020-12-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending'),
        ),
    ]
